# Generated by Django 3.1.7 on 2021-04-13 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('petsCallboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dateadvert',
            options={'ordering': ['id'], 'verbose_name': 'Термін', 'verbose_name_plural': 'Терміни'},
        ),
    ]
